version: 2.1

workflows:
  build-release:
    jobs:
      - build-push:
          context:
            - docker-hub-creds
            - heroku-creds
      - approval-release:
          type: approval
          requires:
            - build-push
      - release:
          requires:
            - approval-release
          context:
            - docker-hub-creds
            - heroku-creds

jobs:
  build-push:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build . -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-$TAG
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-$TAG
          sudo apt-get -qq update && sudo apt-get -qq install aria2
          mkdir env && cd env
          echo 'https://docs.google.com/uc?export=download&id='$DC_FILEID | aria2c --input-file=-
          echo "FROM $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-$TAG
          WORKDIR /usr/src/app
          COPY . .
          " >> Dockerfile
          cat Dockerfile
          echo "Dockerfile created for $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-$TAG"
          heroku container:login
          docker build . -t registry.heroku.com/$CIRCLE_PROJECT_REPONAME-$CIRCLE_BRANCH/worker
          docker push registry.heroku.com/$CIRCLE_PROJECT_REPONAME-$CIRCLE_BRANCH/worker

  release:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run: |
          TAG=0.1.$CIRCLE_PREVIOUS_BUILD_NUM
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker pull $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-$TAG
          docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-$TAG $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-latest
          docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH-latest
          heroku container:login
          heroku container:release worker -a $CIRCLE_PROJECT_REPONAME-$CIRCLE_BRANCH
